/* Version plumbing, shared by sync, check and the tests.
 *
 * version.json is the one hand-maintained version in the project. Everything
 * else that carries a version number is generated from it, because a number
 * that lives in four files by hand is a number that will disagree with itself.
 *
 * Adapted from the versioning contract used in Katsumii. Midori has no Python
 * backend, so the derived set is package.json, both root versions in
 * package-lock.json, and the generated module the renderer reads.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// The official SemVer 2.0.0 pattern: no leading zeroes, optional prerelease
// and build metadata.
const SEMVER = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

export function assertSemver(value) {
  if (typeof value !== 'string' || !SEMVER.test(value)) {
    throw new Error(`Invalid SemVer in version.json: ${JSON.stringify(value)}`);
  }
  return value;
}

export function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, relativePath), 'utf8'));
}

export function readText(relativePath) {
  const target = path.join(ROOT, relativePath);
  return fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
}

export function canonicalVersion() {
  return assertSemver(readJson('version.json').version);
}

/** The module the renderer imports. Generated, never edited by hand. */
export function frontendSource(version) {
  return `// Generated by scripts/sync-version.mjs. Do not edit manually.\n`
    + `export const APP_VERSION = '${version}';\n`;
}

/**
 * Every place the version is out of step, as readable lines.
 *
 * Returns problems rather than throwing on the first one, so a drifted
 * checkout reports all of them at once instead of one per run.
 */
export function collectVersionProblems(version, sources) {
  const problems = [];
  if (sources.packageJson?.version !== version) {
    problems.push(`package.json: ${sources.packageJson?.version}`);
  }
  if (sources.packageLock?.version !== version) {
    problems.push(`package-lock.json: ${sources.packageLock?.version}`);
  }
  if (sources.packageLock?.packages?.['']?.version !== version) {
    problems.push(`package-lock.json packages[""].version: ${sources.packageLock?.packages?.['']?.version}`);
  }
  if (sources.frontend !== frontendSource(version)) {
    problems.push('src/generated/version.js: missing or not synchronized');
  }
  return problems;
}

/**
 * Changelog problems: the top entry has to name the current version, or the
 * app would show release notes for something else as "latest".
 */
export function collectChangelogProblems(version, changelog) {
  const problems = [];
  if (!changelog || !Array.isArray(changelog.releases)) {
    return ['src/data/changelog.json: missing or has no releases array'];
  }
  if (changelog.releases.length === 0) {
    return ['src/data/changelog.json: no releases'];
  }

  const top = changelog.releases[0];
  const expected = `v${version}`;
  if (top.version !== expected) {
    problems.push(`src/data/changelog.json: newest entry is ${top.version}, expected ${expected}`);
  }
  if (!Array.isArray(top.changes) || top.changes.length === 0) {
    problems.push(`src/data/changelog.json: ${top.version} has no changes`);
  }
  return problems;
}

export function writeJson(relativePath, data) {
  fs.writeFileSync(path.join(ROOT, relativePath), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

export function writeText(relativePath, data) {
  const target = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, data, 'utf8');
}
